// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0cnhhW1VATaoyiIqNCxdoXyLioMtBPs',
    appId: '1:647079088665:web:1bcba4ee78b4c93e7f5088',
    messagingSenderId: '647079088665',
    projectId: 'resturent-6fec2',
    authDomain: 'resturent-6fec2.firebaseapp.com',
    storageBucket: 'resturent-6fec2.firebasestorage.app',
    measurementId: 'G-HBX0L7G5E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBBFrMtwuGio9gJnq5-GA9UXDFEbxolU',
    appId: '1:647079088665:android:fe63fdd2db6b65f17f5088',
    messagingSenderId: '647079088665',
    projectId: 'resturent-6fec2',
    storageBucket: 'resturent-6fec2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw0cnhhW1VATaoyiIqNCxdoXyLioMtBPs',
    appId: '1:647079088665:web:28d4f61af334a1197f5088',
    messagingSenderId: '647079088665',
    projectId: 'resturent-6fec2',
    authDomain: 'resturent-6fec2.firebaseapp.com',
    storageBucket: 'resturent-6fec2.firebasestorage.app',
    measurementId: 'G-YHYQ6E0R3P',
  );
}
